name: Periodic health check

# Copied this workflow from exercise 11.19, didn't want to wait again for an hour
# Scheduling should work here since it worked on the exercise, only URL was changed
on:
  push:
    branches:
      - main
  #schedule:
    #- cron: "*/2 * * * *"
  # Disabled this feature after it worked correctly

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-11-20-r01d.onrender.com/
          max-attempts: 3
          retry-delay: 5s