name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dependencies
        working-directory: bloglist-backend
        run: npm install
      - name: Install frontend dependencies
        working-directory: bloglist-frontend
        run: npm install
      - name: Install root dependencies
        run: npm install
      
      - name: Check style for backend
        working-directory: bloglist-backend
        run: npm run lint
      - name: Check style for frontend
        working-directory: bloglist-frontend
        run: npm run lint
      
      - name: Build frontend
        working-directory: bloglist-frontend
        run: npm run build

      - name: Test backend
        working-directory: bloglist-backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
      - name: Test frontend
        working-directory: bloglist-frontend
        run: npm run test

      - name: Print env vars for debugging
        run: |
          echo "TEST_MONGODB_URI is set? ${TEST_MONGODB_URI:+yes}"
          echo "SECRET is set? ${SECRET:+yes}"
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}      
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.ref_name == 'main' && github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch